
#ifndef CONFIGURABLE_DUTY_FREQ_PROJECT_CONFIGURABLED_F_PROJ_H_
#define CONFIGURABLE_DUTY_FREQ_PROJECT_CONFIGURABLED_F_PROJ_H_

void MotorControl_Freq_duty_Runnable (void);
void MotorControl_Freq_duty_Init (void);


#endif /* CONFIGURABLE_DUTY_FREQ_PROJECT_CONFIGURABLED_F_PROJ_H_ */
